services:
  - type: web
    name: v6.chriskrycho.com
    runtime: static
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: 'true'
    buildFilter:
      paths:
        - site/styles/**
        - site/public/**
    staticPublishPath: './site/public'
    domain: v6.chriskrycho.com

  - type: web
    name: music
    runtime: static
    autoDeploy: false
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: 'true'
    buildFilter:
      paths:
        - site/styles/**
        - sites/music/**
    buildCommand: |
      bash ./_scripts/build.sh music

    staticPublishPath: './sites/music/public'
    domain: music.chriskrycho.com
