services:
  - type: web
    name: v6.chriskrycho.com
    runtime: static
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: 'true'
    buildFilter:
      paths:
        - 'site/styles'
        - 'site/public'
    staticPublishPath: './site/public'
    domain: v6.chriskrycho.com

  - type: web
    name: music
    runtime: static
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: 'true'
    buildFilter:
      paths:
        - 'site/styles'
        - 'sites/music'
    buildCommand: |
      # get grass (Rust Sass)
      curl -L --proto '=https' --tlsv1.2 -sSf https://github.com/cargo-bins/cargo-quickinstall/releases/download/grass-0.13.2/grass-0.13.2-x86_64-unknown-linux-musl.tar.gz --output grass.tgz

      # unpack it
      tar -xzf grass.tgz

      # use it build CSS for prod
      ./grass --style=compressed ./sites/music/styles/style.scss ./sites/music/public/style.css

      # copy the HTML to the target directory
      cp ./sites/music/index.html ./sites/music/public/index.html

    staticPublishPath: './sites/music/public'
    domain: music.chriskrycho.com
