[package]
name = "lx"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
# keywords.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
dirs = { workspace = true }
glob = "0.3"
json-feed = { path = "./crates/json-feed" }
lazy_static = { workspace = true }
lx-md = { path = "./crates/markdown" }
normalize-path = "0.2"
rayon = { workspace = true }
regex = "1"
serde = { workspace = true }
serde_yaml = "0.9"
slug = "0.1"
syntect = { workspace = true }
tera = "1"
thiserror = { workspace = true }

[dependencies.atom_syndication]
version = "0.12"
features = ["with-serde"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.uuid]
version = "1"
features = ["serde", "v5"]


################################################################################
#                            Workspace configuration                           #
################################################################################

[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
name = "lx"
version = "1.0.0"
authors = ["Chris Krycho <hello@chriskrycho.com>"]
edition = "2021"
rust-version = "1.70.0"
description = "⚡️ My hyper-specialized tool for building my own website."
repository = "https://github.com/chriskrycho/v6.chriskrycho.com"
homepage = "https://github.com/chriskrycho/v6.chriskrycho.com"
documentation = "https://github.com/chriskrycho/v6.chriskrycho.com"
readme = "README.md"
license = "BlueOak-1.0.0"

[workspace.dependencies]
anyhow = "1"
clap_complete = "4"
dirs = "5"
lazy_static = "1.4"
rayon = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[workspace.dependencies.clap]
version = "4"
features = ["unicode", "cargo", "derive"]

[workspace.dependencies.syntect]
version = "5"
default-features = false
features = ["default-fancy"]
