[package]
name = "lx"
version = "0.1.0"
edition = "2021"
rust-version = "1.67.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "^1.0.0-alpha.7"
tera = "1"
"clap" = { version = "4", features = ["unicode", "derive"] }
clap_complete = "4.1.4"
dirs = "4.0.0"
thiserror = "1.0.38"
